# Generated by Django 4.1.1 on 2022-10-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('roll_no', models.IntegerField()),
                ('profile', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20)),
                ('mark', models.IntegerField()),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Modified_at', models.DateTimeField(auto_now=True)),
                ('student_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='details.student')),
            ],
        ),
    ]
