# Generated by Django 3.2.15 on 2022-10-04 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_mark_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='created_by',
            new_name='updated_by',
        ),
    ]
