# Generated by Django 3.2.15 on 2022-10-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_rename_created_by_mark_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='updated_by',
            field=models.CharField(default='user', max_length=20),
            preserve_default=False,
        ),
    ]
