# Generated by Django 4.1.2 on 2022-10-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_auto_20221004_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
