# Generated by Django 4.1.2 on 2022-10-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0006_alter_mark_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='mail',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
