# Generated by Django 4.1.2 on 2022-10-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_mark_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='mail',
        ),
    ]
