# Generated by Django 4.1.2 on 2022-10-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0009_student_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mail',
            field=models.EmailField(max_length=30, null=True),
        ),
    ]
